name: Label issues on comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  relabel:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7 2026-06-17
        with:
          script: |
            const isOwner = context.payload.comment.author_association === 'OWNER';
            const addLabel = isOwner ? 'Author Reply' : 'User Reply';
            const removeLabel = isOwner ? 'User Reply' : 'Author Reply';
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;

            await github.rest.issues.addLabels({
              owner, repo, issue_number, labels: [addLabel],
            });

            try {
              await github.rest.issues.removeLabel({
                owner, repo, issue_number, name: removeLabel,
              });
            } catch (err) {
              if (err.status !== 404) throw err;
            }
